const subjectGroups = [
    { id: 0, code: "A00", description: "Toán – Vật lí – Hóa học" },
    { id: 1, code: "A01", description: "Toán – Vật lí – Tiếng Anh" },
    { id: 2, code: "A02", description: "Toán – Vật lí – Sinh học" },
    { id: 3, code: "A03", description: "Toán – Vật lí – Lịch sử" },
    { id: 4, code: "A04", description: "Toán – Vật lí – Địa lí" },
    { id: 5, code: "A05", description: "Toán – Hóa học – Lịch sử" },
    { id: 6, code: "A06", description: "Toán – Hóa học – Địa lí" },
    { id: 7, code: "A07", description: "Toán – Lịch sử – Địa lí" },
    { id: 8, code: "A08", description: "Toán – Lịch sử – Giáo dục công dân" },
    { id: 9, code: "A09", description: "Toán – Địa lý – Giáo dục công dân" },
    { id: 10, code: "A10", description: "Toán – Lý – Giáo dục công dân" },
    { id: 11, code: "A11", description: "Toán – Hóa – Giáo dục công dân" },
    { id: 12, code: "A12", description: "Toán – Khoa học tự nhiên – KH xã hội" },
    { id: 13, code: "A14", description: "Toán – Khoa học tự nhiên – Địa lí" },
    { id: 14, code: "A15", description: "Toán – KH tự nhiên – Giáo dục công dân" },
    { id: 15, code: "A16", description: "Toán – Khoa học tự nhiên – Ngữ văn" },
    { id: 16, code: "A17", description: "Toán – Vật lý – Khoa học xã hội" },
    { id: 17, code: "A18", description: "Toán – Hóa học – Khoa học xã hội" },
    { id: 18, code: "B00", description: "Toán – Hóa học – Sinh học" },
    { id: 19, code: "B01", description: "Toán – Sinh học – Lịch sử" },
    { id: 20, code: "B02", description: "Toán – Sinh học – Địa lí" },
    { id: 21, code: "B03", description: "Toán – Sinh học – Ngữ văn" },
    { id: 22, code: "B04", description: "Toán – Sinh học – Giáo dục công dân" },
    { id: 23, code: "B05", description: "Toán – Sinh học – Khoa học xã hội" },
    { id: 24, code: "B06", description: "Toán – Sinh học – Tiếng Anh" },
    { id: 25, code: "C00", description: "Ngữ văn – Lịch sử – Địa lí" },
    { id: 26, code: "C01", description: "Ngữ văn – Toán – Vật lí" },
    { id: 27, code: "C02", description: "Ngữ văn – Toán – Hóa học" },
    { id: 28, code: "C03", description: "Ngữ văn – Toán – Lịch sử" },
    { id: 29, code: "C04", description: "Ngữ văn – Toán – Địa lí" },
    { id: 30, code: "C05", description: "Ngữ văn – Vật lí – Hóa học" },
    { id: 31, code: "C06", description: "Ngữ văn – Vật lí – Sinh học" },
    { id: 32, code: "C07", description: "Ngữ văn – Vật lí – Lịch sử" },
    { id: 33, code: "C08", description: "Ngữ văn – Hóa học – Sinh học" },
    { id: 34, code: "C09", description: "Ngữ văn – Vật lí – Địa lí" },
    { id: 35, code: "C10", description: "Ngữ văn – Hóa học – Lịch sử" },
    { id: 36, code: "C12", description: "Ngữ văn – Sinh học – Lịch sử" },
    { id: 37, code: "C13", description: "Ngữ văn – Sinh học – Địa lí" },
    { id: 38, code: "C14", description: "Ngữ văn – Toán – Giáo dục công dân" },
    { id: 39, code: "C15", description: "Ngữ văn – Toán – Khoa học xã hội" },
    { id: 40, code: "C16", description: "Ngữ văn – Vật lí – Giáo dục công dân" },
    { id: 41, code: "C17", description: "Ngữ văn – Hóa học – Giáo dục công dân" },
    { id: 42, code: "C19", description: "Ngữ văn – Lịch sử – Giáo dục công dân" },
    { id: 43, code: "C20", description: "Ngữ văn – Địa lí – Giáo dục công dân" },
    { id: 44, code: "D01", description: "Ngữ văn – Toán – Tiếng Anh" },
    { id: 45, code: "D02", description: "Ngữ văn – Toán – Tiếng Nga" },
    { id: 46, code: "D03", description: "Ngữ văn – Toán – Tiếng Pháp" },
    { id: 47, code: "D04", description: "Ngữ văn – Toán – Tiếng Trung" },
    { id: 48, code: "D05", description: "Ngữ văn – Toán – Tiếng Đức" },
    { id: 49, code: "D06", description: "Ngữ văn – Toán – Tiếng Nhật" },
    { id: 50, code: "D07", description: "Toán – Hóa học – Tiếng Anh" },
    { id: 51, code: "D08", description: "Toán – Sinh học – Tiếng Anh" },
    { id: 52, code: "D09", description: "Toán – Lịch sử – Tiếng Anh" },
    { id: 53, code: "D10", description: "Toán – Địa lí – Tiếng Anh" },
    { id: 54, code: "D11", description: "Ngữ văn – Vật lí – Tiếng Anh" },
    { id: 55, code: "D12", description: "Ngữ văn – Hóa học – Tiếng Anh" },
    { id: 56, code: "D13", description: "Ngữ văn – Sinh học – Tiếng Anh" },
    { id: 57, code: "D14", description: "Ngữ văn – Lịch sử – Tiếng Anh" },
    { id: 58, code: "D15", description: "Ngữ văn – Địa lí – Tiếng Anh" },
    { id: 59, code: "D16", description: "Toán – Địa lí – Tiếng Đức" },
    { id: 60, code: "D17", description: "Toán – Địa lí – Tiếng Nga" },
    { id: 61, code: "D18", description: "Toán – Địa lí – Tiếng Nhật" },
    { id: 62, code: "D19", description: "Toán – Địa lí – Tiếng Pháp" },
    { id: 63, code: "D20", description: "Toán – Địa lí – Tiếng Trung" },
    { id: 64, code: "D21", description: "Toán – Hóa học – Tiếng Đức" },
    { id: 65, code: "D22", description: "Toán – Hóa học – Tiếng Nga" },
    { id: 66, code: "D23", description: "Toán – Hóa học – Tiếng Nhật" },
    { id: 67, code: "D24", description: "Toán – Hóa học – Tiếng Pháp" },
    { id: 68, code: "D25", description: "Toán – Hóa học – Tiếng Trung" },
    { id: 69, code: "D26", description: "Toán – Vật lí – Tiếng Đức" },
    { id: 70, code: "D27", description: "Toán – Vật lí – Tiếng Nga" },
    { id: 71, code: "D28", description: "Toán – Vật lí – Tiếng Nhật" },
    { id: 72, code: "D29", description: "Toán – Vật lí – Tiếng Pháp" },
    { id: 73, code: "D30", description: "Toán – Vật lí – Tiếng Trung" },
    { id: 74, code: "D31", description: "Toán – Sinh học – Tiếng Đức" },
    { id: 75, code: "D32", description: "Toán – Sinh học – Tiếng Nga" },
    { id: 76, code: "D33", description: "Toán – Sinh học – Tiếng Nhật" },
    { id: 77, code: "D34", description: "Toán – Sinh học – Tiếng Pháp" },
    { id: 78, code: "D35", description: "Toán – Sinh học – Tiếng Trung" },
    { id: 79, code: "D41", description: "Ngữ văn – Địa lí – Tiếng Đức" },
    { id: 80, code: "D42", description: "Ngữ văn – Địa lí – Tiếng Nga" },
    { id: 81, code: "D43", description: "Ngữ văn – Địa lí – Tiếng Nhật" },
    { id: 82, code: "D44", description: "Ngữ văn – Địa lí – Tiếng Pháp" },
    { id: 83, code: "D45", description: "Ngữ văn – Địa lí – Tiếng Trung" },
    { id: 84, code: "D52", description: "Ngữ văn – Vật lí – Tiếng Nga" },
    { id: 85, code: "D54", description: "Ngữ văn – Vật lí – Tiếng Pháp" },
    { id: 86, code: "D55", description: "Ngữ văn – Vật lí – Tiếng Trung" },
    { id: 87, code: "D61", description: "Ngữ văn – Lịch sử – Tiếng Đức" },
    { id: 88, code: "D62", description: "Ngữ văn – Lịch sử – Tiếng Nga" },
    { id: 89, code: "D63", description: "Ngữ văn – Lịch sử – Tiếng Nhật" },
    { id: 90, code: "D64", description: "Ngữ văn – Lịch sử – Tiếng Pháp" },
    { id: 91, code: "D65", description: "Ngữ văn – Lịch sử – Tiếng Trung" },
    { id: 92, code: "D66", description: "Ngữ văn – Giáo dục công dân – Tiếng Anh" },
    { id: 93, code: "D68", description: "Ngữ văn – Giáo dục công dân – Tiếng Nga" },
    { id: 94, code: "D69", description: "Ngữ Văn – Giáo dục công dân – Tiếng Nhật" },
    { id: 95, code: "D70", description: "Ngữ Văn – Giáo dục công dân – Tiếng Pháp" },
    { id: 96, code: "D72", description: "Ngữ văn – Khoa học tự nhiên – Tiếng Anh" },
    { id: 97, code: "D73", description: "Ngữ văn – Khoa học tự nhiên – Tiếng Đức" },
    { id: 98, code: "D74", description: "Ngữ văn – Khoa học tự nhiên – Tiếng Nga" },
    { id: 99, code: "D75", description: "Ngữ văn – Khoa học tự nhiên – Tiếng Nhật" },
    { id: 100, code: "D76", description: "Ngữ văn – Khoa học tự nhiên – Tiếng Pháp" },
    { id: 101, code: "D77", description: "Ngữ văn – Khoa học tự nhiên – Tiếng Trung" },
    { id: 102, code: "D78", description: "Ngữ văn – Khoa học xã hội – Tiếng Anh" },
    { id: 103, code: "D79", description: "Ngữ văn – Khoa học xã hội – Tiếng Đức" },
    { id: 104, code: "D80", description: "Ngữ văn – Khoa học xã hội – Tiếng Nga" },
    { id: 105, code: "D81", description: "Ngữ văn – Khoa học xã hội – Tiếng Nhật" },
    { id: 106, code: "D82", description: "Ngữ văn – Khoa học xã hội – Tiếng Pháp" },
    { id: 107, code: "D83", description: "Ngữ văn – Khoa học xã hội – Tiếng Trung" },
    { id: 108, code: "D84", description: "Toán – Giáo dục công dân – Tiếng Anh" },
    { id: 109, code: "D85", description: "Toán – Giáo dục công dân – Tiếng Đức" },
    { id: 110, code: "D86", description: "Toán – Giáo dục công dân – Tiếng Nga" },
    { id: 111, code: "D87", description: "Toán – Giáo dục công dân – Tiếng Pháp" },
    { id: 112, code: "D88", description: "Toán – Giáo dục công dân – Tiếng Nhật" },
    { id: 113, code: "D90", description: "Toán – Khoa học tự nhiên – Tiếng Anh" },
    { id: 114, code: "D91", description: "Toán – Khoa học tự nhiên – Tiếng Pháp" },
    { id: 115, code: "D92", description: "Toán – Khoa học tự nhiên – Tiếng Đức" },
    { id: 116, code: "D93", description: "Toán – Khoa học tự nhiên – Tiếng Nga" },
    { id: 117, code: "D94", description: "Toán – Khoa học tự nhiên – Tiếng Nhật" },
    { id: 118, code: "D95", description: "Toán – Khoa học tự nhiên – Tiếng Trung" },
    { id: 119, code: "D96", description: "Toán – Khoa học xã hội – Tiếng Anh" },
    { id: 120, code: "D97", description: "Toán – Khoa học xã hội – Tiếng Pháp" },
    { id: 121, code: "D98", description: "Toán – Khoa học xã hội – Tiếng Đức" },
    { id: 122, code: "D99", description: "Toán – Khoa học xã hội – Tiếng Nga" },
    { id: 123, code: "H00", description: "Ngữ văn – Năng khiếu vẽ Nghệ thuật 1 – Năng khiếu vẽ Nghệ thuật 2" },
    { id: 124, code: "H01", description: "Toán – Ngữ văn – Vẽ" },
    { id: 125, code: "H02", description: "Toán – Vẽ Hình họa mỹ thuật – Vẽ trang trí màu" },
    { id: 126, code: "H03", description: "Toán – Khoa học tự nhiên – Vẽ Năng khiếu" },
    { id: 127, code: "H04", description: "Toán – Tiếng Anh – Vẽ Năng khiếu" },
    { id: 128, code: "H05", description: "Ngữ văn – Khoa học xã hội – Vẽ Năng khiếu" },
    { id: 129, code: "H06", description: "Ngữ văn – Tiếng Anh – Vẽ mỹ thuật" },
    { id: 130, code: "H07", description: "Toán – Hình họa – Trang trí" },
    { id: 131, code: "H08", description: "Ngữ văn – Lịch sử – Vẽ mỹ thuật" },
    { id: 132, code: "K01", description: "Toán – Tiếng Anh – Tin học" },
    { id: 133, code: "M00", description: "Ngữ văn – Toán – Đọc diễn cảm – Hát" },
    { id: 134, code: "M01", description: "Ngữ văn – Lịch sử – Năng khiếu" },
    { id: 135, code: "M02", description: "Toán – Năng khiếu 1 – Năng khiếu 2" },
    { id: 136, code: "M03", description: "Văn – Năng khiếu 1 – Năng khiếu 2" },
    { id: 137, code: "M04", description: "Toán – Đọc kể diễn cảm – Hát Múa" },
    { id: 138, code: "M09", description: "Toán – NK Mầm non 1 (kể chuyện, đọc, diễn cảm) – NK Mầm non 2 (Hát)" },
    { id: 139, code: "M10", description: "Toán – Tiếng Anh – NK1" },
    { id: 140, code: "M11", description: "Ngữ văn – Năng khiếu báo chí – Tiếng Anh" },
    { id: 141, code: "M13", description: "Toán – Sinh học – Năng khiếu" },
    { id: 142, code: "M14", description: "Ngữ văn – Năng khiếu báo chí – Toán" },
    { id: 143, code: "M15", description: "Ngữ văn – Năng khiếu báo chí – Tiếng Anh" },
    { id: 144, code: "M16", description: "Ngữ văn – Năng khiếu báo chí – Vật lí" },
    { id: 145, code: "M17", description: "Ngữ văn – Năng khiếu báo chí – Lịch sử" },
    { id: 146, code: "M18", description: "Ngữ văn – Năng khiếu Ảnh báo chí – Toán" },
    { id: 147, code: "M19", description: "Ngữ văn – Năng khiếu Ảnh báo chí – Tiếng Anh" },
    { id: 148, code: "M20", description: "Ngữ văn – Năng khiếu Ảnh báo chí – Vật lí" },
    { id: 149, code: "M21", description: "Ngữ văn – Năng khiếu Ảnh báo chí – Lịch sử" },
    { id: 150, code: "M22", description: "Ngữ văn – Năng khiếu quay phim truyền hình – Toán" },
    { id: 151, code: "M23", description: "Ngữ văn – Năng khiếu quay phim truyền hình – Tiếng Anh" },
    { id: 152, code: "M24", description: "Ngữ văn – Năng khiếu quay phim truyền hình – Vật lí" },
    { id: 153, code: "M25", description: "Ngữ văn – Năng khiếu quay phim truyền hình – Lịch sử" },
    { id: 154, code: "N00", description: "Ngữ văn – Năng khiếu Âm nhạc 1 – Năng khiếu Âm nhạc 2" },
    { id: 155, code: "N01", description: "Ngữ văn – xướng âm, biểu diễn nghệ thuật" },
    { id: 156, code: "N02", description: "Ngữ văn – Ký xướng âm – Hát hoặc biểu diễn nhạc cụ" },
    { id: 157, code: "N03", description: "Ngữ văn – Ghi âm-xướng âm, chuyên môn" },
    { id: 158, code: "N04", description: "Ngữ Văn – Năng khiếu thuyết trình – Năng khiếu" },
    { id: 159, code: "N05", description: "Ngữ Văn – Xây dựng kịch bản sự kiện – Năng khiếu" },
    { id: 160, code: "N06", description: "Ngữ văn – Ghi âm, xướng âm – Chuyên môn" },
    { id: 161, code: "N07", description: "Ngữ văn – Ghi âm, xướng âm – Chuyên môn" },
    { id: 162, code: "N08", description: "Ngữ văn – Hòa thanh – Phát triển chủ đề và phổ thơ" },
    { id: 163, code: "N09", description: "Ngữ văn – Hòa thanh – Bốc thăm đề, chỉ huy tại chỗ" },
    { id: 164, code: "R00", description: "Ngữ văn – Lịch sử – Năng khiếu báo chí" },
    { id: 165, code: "R01", description: "Ngữ văn – Địa lý – Năng khiếu Biểu diễn nghệ thuật" },
    { id: 166, code: "R02", description: "Ngữ văn – Toán – Năng khiếu Biểu diễn nghệ thuật" },
    { id: 167, code: "R03", description: "Ngữ văn – Tiếng Anh – Năng khiếu Biểu diễn nghệ thuật" },
    { id: 168, code: "R04", description: "Ngữ văn – Năng khiếu Biểu diễn nghệ thuật – Năng khiếu Kiến thức văn hóa – xã hội – nghệ thuật" },
    { id: 169, code: "R05", description: "Ngữ văn – Tiếng Anh – Năng khiếu kiến thức truyền thông" },
    { id: 170, code: "S00", description: "Ngữ văn – Năng khiếu SKĐA 1 – Năng khiếu SKĐA 2" },
    { id: 171, code: "S01", description: "Toán – Năng khiếu 1 – Năng khiếu 2" },
    { id: 172, code: "T00", description: "Toán – Sinh học – Năng khiếu TDTT" },
    { id: 173, code: "T01", description: "Toán – Ngữ văn – Năng khiếu TDTT" },
    { id: 174, code: "T02", description: "Ngữ văn – Sinh – Năng khiếu TDTT" },
    { id: 175, code: "T03", description: "Ngữ văn – Địa – Năng khiếu TDTT" },
    { id: 176, code: "T04", description: "Toán – Lý – Năng khiếu TDTT" },
    { id: 177, code: "T05", description: "Ngữ văn – Giáo dục công dân – Năng khiếu" },
    { id: 178, code: "V00", description: "Toán – Vật lí – Vẽ Hình họa mỹ thuật" },
    { id: 179, code: "V01", description: "Toán – Ngữ văn – Vẽ Hình họa mỹ thuật" },
    { id: 180, code: "V02", description: "Vẽ mỹ thuật – Toán – Tiếng Anh" },
    { id: 181, code: "V03", description: "Vẽ mỹ thuật – Toán – Hóa" },
    { id: 182, code: "V05", description: "Ngữ văn – Vật lí – Vẽ mỹ thuật" },
    { id: 183, code: "V06", description: "Toán – Địa lí – Vẽ mỹ thuật" },
    { id: 184, code: "V07", description: "Toán – tiếng Đức – Vẽ mỹ thuật" },
    { id: 185, code: "V08", description: "Toán – tiếng Nga – Vẽ mỹ thuật" },
    { id: 186, code: "V09", description: "Toán – tiếng Nhật – Vẽ mỹ thuật" },
    { id: 187, code: "V10", description: "Toán – tiếng Pháp – Vẽ mỹ thuật" },
    { id: 188, code: "V11", description: "Toán – tiếng Trung – Vẽ mỹ thuật" }
];

export default subjectGroups;